---
up: [[Java Core]]
---
# Исключения
---
###### [[Общие вопросы по исключениям]]
![[Общие вопросы по исключениям#Что такое исключения?]]

![[Общие вопросы по исключениям#Опишите иерархию исключений]]

![[Общие вопросы по исключениям#Расскажите про обрабатываемые и необрабатываемые исключения]]

![[Общие вопросы по исключениям#Что происходит при необработанном исключении?]]

![[Общие вопросы по исключениям#Можно ли обработать необрабатываемые исключения?]]

![[Общие вопросы по исключениям#Как создать, выбросить, поймать свое исключение?]]

![[Общие вопросы по исключениям#Какой оператор позволяет принудительно выбросить исключение?]]

![[Общие вопросы по исключениям#Где возможно вызывать исключения?]]

![[Общие вопросы по исключениям#В чем разница между throw и throws?]]

![[Общие вопросы по исключениям#Может ли метод main() выбросить исключение во вне и если да, то где будет происходить обработка данного исключения?]]

![[Общие вопросы по исключениям#Что такое подавленные исключения?]]

![[Общие вопросы по исключениям#Как достать подавленное исключение?]]

###### [[Классы Exception и Throwable]]
![[Классы Exception и Throwable#Какое назначение класса Throwable? Методы класса Throwable]]

![[Классы Exception и Throwable#От каких классов Throwable и его подклассов нельзя наследоваться?]]

![[Классы Exception и Throwable#Расскажи про информацию, которая находится внутри исключения? Как с ней работать?]]

![[Классы Exception и Throwable#Назвать проверяемые исключения?]]

![[Классы Exception и Throwable#В чем разница между Exception и Error?]]

![[Классы Exception и Throwable#Что такое OutOfMemoryError?]]

###### [[try-catch-finaly]]
![[try-catch-finaly#Расскажите про механизм обработки исключений в java (Try-catch-finally)]]

![[try-catch-finaly#Может ли один блок catch отлавливать сразу несколько исключений?]]

![[try-catch-finaly#В каком порядке следует обрабатывать исключения в catch блоках?]]

![[try-catch-finaly#Может ли исключение быть снова брошено после перехвата?]]

![[try-catch-finaly#Можем ли мы написать несколько блоков catch в одном блоке try?]]

![[try-catch-finaly#Можно ли так написать try { throw new Object(); }?]]

![[try-catch-finaly#Для чего в основном используется блок finally?]]

![[try-catch-finaly#Возможно ли использование блока try-finally (без catch)?]]

![[try-catch-finaly#Всегда ли выполняется блок finally? Существуют ли ситуации, когда блок finally не будет выполнен?]]

![[try-catch-finaly#Что произойдет если исключение будет выброшено из блока catch после чего другое исключение будет выброшено из блока finally?]]

![[try-catch-finaly#Что если в конструкции try finally вылетело исключение сначала в try а потом в finally? Какое исключение вылетит? Что будет с другим?]]

![[try-catch-finaly#Какой return вернется? Из try или finaly?]]

###### [[try-with-resources]]
![[try-with-resources#Что такое механизм try-with-resources?]]

![[try-with-resources#Какие интерфейсы должен имплементировать объект в try с ресурсами. Их отличия?]]

![[try-with-resources#Что такое ресурс в конструкции try-with-resources?]]

![[try-with-resources#Когда происходит закрытие ресурса в конструкции try-with-resources если в try возникло исключение: до перехода в catch или после того как catch отработает?]]

![[try-with-resources#Что произойдет если исключение будет выброшено из блока catch после чего другое исключение будет выброшено из метода close() при использовании try-with-resources?]]

###### [[StackTrace]]
![[StackTrace#Что такое StackTrace. Какую информацию из него можно получить?]]

![[StackTrace#Что возвращает getStackTrace()?]]

![[StackTrace#Какую информацию можно получить из StackTraceElement?]]
